---
- name: Create Materialized view
  community.postgresql.postgresql_query:
    login_host: "{{ db_ip }}"
    port: "{{ db_port }}"
    db: "{{ db_name }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    query: "{{ item.query }}"
    search_path: "{{ schema }}"
  with_items:
    - { query: "CREATE MATERIALIZED VIEW mv_shelve_count AS SELECT c.name AS category_name, SUM(pos.product_count) AS shelves_count FROM products_on_shelves pos JOIN product_categories pc ON pos.product_id = pc.product_id JOIN categories c ON pc.category_id = c.category_id WHERE pos.product_count IS NOT NULL GROUP BY c.name;" }
    - { query: "CREATE MATERIALIZED VIEW mv_external_supplies AS SELECT es.finish_date AS date, c.name AS category_name FROM external_supplies es LEFT JOIN external_supplies_products esp ON esp.ext_supply_id = es.ext_supply_id LEFT JOIN product_categories pc ON esp.product_id = pc.product_id LEFT JOIN categories c ON pc.category_id = c.category_id GROUP BY es.finish_date, c.name ORDER BY es.finish_date ASC;" }
    - { query: "CREATE MATERIALIZED VIEW mv_product_summary AS SELECT ch.issue_date AS date, cat.name AS category_name, SUM(pcp.product_count) AS sum_products_issue_date FROM checks ch LEFT JOIN product_check_positions pcp ON pcp.check_id = ch.check_id LEFT JOIN product_categories pc ON pcp.product_id = pc.product_id LEFT JOIN categories cat ON pc.category_id = cat.category_id WHERE pcp.product_count IS NOT NULL GROUP BY ch.issue_date, cat.name ORDER BY ch.issue_date ASC;" }
  ignore_errors: True
  tags: create-materialized-view