ALTER TABLE categories ADD PRIMARY KEY (category_id);
ALTER TABLE checks ADD PRIMARY KEY (check_id);
ALTER TABLE external_supplies ADD PRIMARY KEY (ext_supply_id);
ALTER TABLE locations ADD PRIMARY KEY (location_id);
ALTER TABLE supplies ADD PRIMARY KEY (supply_id);
ALTER TABLE products ADD PRIMARY KEY (product_id);
ALTER TABLE warehouses ADD PRIMARY KEY (warehouse_id);
ALTER TABLE stores ADD PRIMARY KEY (store_id);
ALTER TABLE shelves ADD PRIMARY KEY (shelve_id);

ALTER TABLE checks_stores ADD CONSTRAINT fk_checks_stores_check FOREIGN KEY (check_id) REFERENCES checks (check_id), ADD CONSTRAINT fk_checks_stores_store FOREIGN KEY (store_id) REFERENCES stores (store_id);
ALTER TABLE supplies_stores ADD CONSTRAINT fk_supplies_stores_supply FOREIGN KEY (supply_id) REFERENCES supplies (supply_id), ADD CONSTRAINT fk_supplies_stores_store FOREIGN KEY (store_id) REFERENCES stores (store_id);
ALTER TABLE product_categories ADD CONSTRAINT fk_product_categories_product FOREIGN KEY (product_id) REFERENCES products (product_id), ADD CONSTRAINT fk_product_categories_category FOREIGN KEY (category_id) REFERENCES categories (category_id);
ALTER TABLE warehouse_locations ADD CONSTRAINT fk_warehouse_locations_location FOREIGN KEY (location_id) REFERENCES locations (location_id), ADD CONSTRAINT fk_warehouse_locations_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (warehouse_id);
ALTER TABLE store_locations ADD CONSTRAINT fk_store_locations_location FOREIGN KEY (location_id) REFERENCES locations (location_id), ADD CONSTRAINT fk_store_locations_store FOREIGN KEY (store_id) REFERENCES stores (store_id);
ALTER TABLE supplies_warehouses ADD CONSTRAINT fk_supplies_warehouses_supply FOREIGN KEY (supply_id) REFERENCES supplies (supply_id), ADD CONSTRAINT fk_supplies_warehouses_warehouses FOREIGN KEY (warehouse_id) REFERENCES warehouses (warehouse_id);
ALTER TABLE external_supplies_products ADD CONSTRAINT fk_external_supplies_products_ext_supply FOREIGN KEY (ext_supply_id) REFERENCES external_supplies (ext_supply_id), ADD CONSTRAINT fk_external_supplies_products_product FOREIGN KEY (product_id) REFERENCES products (product_id);
ALTER TABLE product_check_positions ADD CONSTRAINT fk_product_check_positions_check FOREIGN KEY (check_id) REFERENCES checks (check_id), ADD CONSTRAINT fk_product_check_positions_product FOREIGN KEY (product_id) REFERENCES products (product_id);
ALTER TABLE supplies_products ADD CONSTRAINT fk_supplies_products_supply FOREIGN KEY (supply_id) REFERENCES supplies (supply_id), ADD CONSTRAINT fk_supplies_products_product FOREIGN KEY (product_id) REFERENCES products (product_id);

CREATE INDEX categories_idx ON categories (category_id);
CREATE INDEX checks_idx ON checks (check_id);
CREATE INDEX checks_stores_idx ON checks_stores (check_id, store_id);
CREATE INDEX external_supplies_idx ON external_supplies (ext_supply_id);
CREATE INDEX external_supplies_products_idx ON external_supplies_products (ext_supply_id, product_id);
CREATE INDEX external_supplies_warehouses_idx ON external_supplies_warehouses (ext_supply_id, warehouse_id, shelve_id);
CREATE INDEX locations_idx ON locations (location_id);
CREATE INDEX products_idx ON products (product_id);
CREATE INDEX products_on_shelves_idx ON products_on_shelves (product_id, shelve_id);
CREATE INDEX shelves_idx ON shelves (shelve_id);
CREATE INDEX store_locations_idx ON store_locations (store_id, location_id);
CREATE INDEX stores_idx ON stores (store_id);
CREATE INDEX supplies_idx ON supplies (supply_id);
CREATE INDEX supplies_products_idx ON supplies_products (supply_id, product_id);
CREATE INDEX supplies_warehouses_idx ON supplies_warehouses (supply_id, warehouse_id, shelve_id);
CREATE INDEX supplies_stores_idx ON supplies_stores (supply_id, store_id);
CREATE INDEX warehouse_locations_idx ON warehouse_locations (warehouse_id, location_id);
CREATE INDEX warehouse_shelves_idx ON warehouse_shelves (warehouse_id, shelve_id);
CREATE INDEX warehouses_idx ON warehouses (warehouse_id);
