#!/Users/test/SandBox/KIT/KITHW8/venv/bin/python3.12
# -*- coding: utf-8 -*-
import re
import sys
from streamlit.web.cli import main
import before_database
from draw import draw_graph

before_database.init_data_small()
before_database.init_date_prod()

events, shelves_count, categories = before_database.take_data('prod')
graph_data_prod, index_prod = draw_graph(events, shelves_count, categories)

events, shelves_count, categories = before_database.take_data('small')
graph_data_small, index_small = draw_graph(events, shelves_count, categories)

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
